version: '3.4'

services:
  moveparent:
    image: moveparent
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8888:8888
      - 9229:9229
